#!/usr/bin/env perl

use warnings;
use strict;
use lib '/home/imp25/urop/perl/gwybodaeth';
use lib '/home/imp25/urop/perl/gwybodaeth/Parsers';

my $data = shift;

my $map = shift;

use Read;
use GeoNamesXML;
use N3;
use WriteFromXML;

my $input = Read->new();

my $len;
if (-f $data) {
    $len = $input->get_file_data($data);
} else {
    $len = $input->get_url_data($data);
}

die "Empty site" if ($len < 1);

my $mapping = Read->new();

if (-f $map) {
    $len = $mapping->get_file_data($map);
} else {
    $len = $mapping->get_url_data($map);
}

die "Empty map" if ($len < 1);

my $xml = GeoNamesXML->new();

my $xml_data_ref = $xml->parse(@{ $input->get_input_data });

my $m = N3->new();
my $map_triples = $m->parse(@{ $mapping->get_input_data });

my $write = WriteFromXML->new();

$write->write_rdf($map_triples, $xml_data_ref);
