#!/usr/bin/env perl

use warnings;
use strict;
use lib '/home/imp25/urop/perl/gwybodaeth';
use lib '/home/imp25/urop/perl/gwybodaeth/Parsers';

my $data = shift;
my $map = shift;

use Read;
use N3;

my $input = Read->new();

my $len;
if (-f $data) {
    $len = $input->get_file_data($data);
} else {
    $len = $input->get_url_data($data);
}

die "Empty file." if ($len < 1);

my $mapping = Read->new();

if (-f $map) {
    $len = $mapping->get_file_data($map);
} else {
    $len = $mapping->get_url_data($map);
}

die "Empty site." if ($len < 1);

my @data = $mapping->get_input_data;

my $parser = N3->new();

my $map_triples = $parser->parse(@data);

use CSV;

my $csv = CSV->new();

my $csv_data_ref = $csv->parse($input->get_input_data);

use Write;

my $write = Write->new();

$write->write_rdf($map_triples,
                  $csv_data_ref);
